### ISSUE TITLE
[BUG] Website shows mobile layout in pc browser - High Priority

### ISSUE THREAD

**Issue by BHuber-DSKI** [dskobe/website#48]
Browser: Chrome

Issue quote "By the way something is wrong with our DSKI school website page.  The Saturday school details cannot be accessed on the computer properly and efficiently when I open the school page.  The pages that open are suitable for use on a mobile phone perhaps but not for a computer because the data and access is out of whack.  Previously the page was in a better format but suddenly has changed to the mobile app format which is not suitable for opening the school pages on a computer. Please check immediately and resolve."

**Comment by dkastl** [comment]
I can't reproduce the problem. It works on Chrome and on Firefox without any problem.

There was an udpate yesterday evening that removed the slider image and re-enabled slide animation. Maybe bad timing to access the site and a brwoser cache issue, but also Alex wrote me this morning and said the site looks great.

Just as a side note, I find the tone the issue is written not appropriate. Who wrote this? I see that you quoted it, so I assume this is not from you.

**Comment by BHuber-DSKI** [comment]
> Just as a side note, I find the tone the issue is written not appropriate. Who wrote this? I see that you quoted it, so I assume this is not from you.

I just forward it from Cecil. That's how he talks with us...
